config/routes.rb
Rails.application.routes.draw do

  resources :user_projects

  resources :artifacts

  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end

  resources :members

  get 'home/index'

  root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match 'user/confirmation' => 'confirmations#update', :via => :put,
    :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan

  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

 acts_as_universal_and_determines_tenant
 has_many :members, dependent: :destroy
 has_many :projects, dependent: :destroy
 has_one :payment
 accepts_nested_attributes_for :payment

 validates_presence_of :name
 validates_uniqueness_of :name

 def can_create_projects?
  (plan == 'free' && projects.count < 1) || (plan == 'premium')
 end

 def self.create_new_tenant(tenant_params, user_params, coupon_params)

  tenant = Tenant.new(tenant_params)

  if new_signups_not_permitted?(coupon_params)

    raise ::Milia::Control::MaxTenantExceeded, "Sorry, new accounts not permitted at this time"

  else
        tenant.save    # create the tenant
      end
      return tenant
    end

  # ------------------------------------------------------------------------
  # new_signups_not_permitted? -- returns true if no further signups allowed
  # args: params from user input; might contain a special 'coupon' code
  #       used to determine whether or not to allow another signup
  # ------------------------------------------------------------------------
  def self.new_signups_not_permitted?(params)
    return false
  end

  # ------------------------------------------------------------------------
  # tenant_signup -- setup a new tenant in the system
  # CALLBACK from devise RegistrationsController (milia override)
  # AFTER user creation and current_tenant established
  # args:
  #   user  -- new user  obj
  #   tenant -- new tenant obj
  #   other  -- any other parameter string from initial request
  # ------------------------------------------------------------------------
  def self.tenant_signup(user, tenant, other = nil)
      #  StartupJob.queue_startup( tenant, user, other )
      # any special seeding required for a new organizational tenant
      #
      Member.create_org_admin(user)
      #
    end


  end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController

  before_action :set_tenant

  def edit
  end

  def update
    respond_to do |format|
      Tenant.transaction do
        if @tenant.update(tenant_params)
          if @tenant.plan == 'premium' && @tenant.payment.blank?
            @payment = Payment.new({ email: tenant_params["email"],
              token: params[:payment]["token"],
              tenant: @tenant })
            begin
              @payment.process_payment
              @payment.save
            rescue Exception => e
              flash[:error] = e.message
              @payment.destroy
              @tenant.plan = 'free'
              @tenant.save
              redirect_to edit_tenant_path(@tenant) and return
            end
          end
          format.html { redirect_to edit_plan_path, notice: 'Plan was successfully updated.'}
        else
          format.html { render :edit }
        end
      end
    end
  end

  def change
    @tenant = Tenant.find(params[:id])
    Tenant.set_current_tenant @tenant.id
    session[:tenant_id] = Tenant.current_tenant.id
    redirect_to home_index_path, notice: "Switched to organization #{@tenant.name}"
  end

  private

  def set_tenant
    @tenant = Tenant.find(Tenant.current_tenant_id)
  end

  def tenant_params
    params.require(:tenant).permit(:name, :plan)
  end

  private

  def set_tenant
    @tenant = Tenant.find(Tenant.current_tenant_id)
  end

end

app/views/tenants/edit.html.erb
<script language="JavaScript">
  Stripe.setPublishableKey("<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>");
</script>
<%= form_for @tenant, url: update_plan_path, html: { class: "#{class_name_for_tenant_form(@tenant)}" } do |f| %>
<div class="form-group col-md-12 no-side-padding">
  <%= f.label :name, 'Organization' %>
  <span class='description'>(Unique name for your group or organization for the new account)</span>
  <%= f.text_field :name, required: true, class: "form-control" %>
</div>
<div class="form-group col-md-12 no-side-padding">
  <%= f.label :plan %>
  <%= f.select :plan, options_for_select(Plan.options, @tenant.plan ), {}, required: true, class: "form-control" %>
</div>
<% if @tenant.payment.blank? %>
<%= fields_for( :payment ) do |p| %>
<div class="row col-md-12">
  <div class="form-group col-md-4 no-left-padding">
    <%= p.label :card_number, "Card Number", data: { stripe: 'label' } %>
    <%= p.text_field :card_number, class: "form-control", required: true,
    data: { stripe: 'number' } %>
  </div>
  <div class="form-group col-md-2">
    <%= p.label :card_cvv, "Card CVV", data: { stripe: 'label' } %>
    <%= p.text_field :card_cvv, class: "form-control", required: true,
    data: { stripe: 'cvv' } %>
  </div>
  <div class="form-group col-md-6">
    <div class="col-md-12">
      <%= p.label :card_expires, "Card Expires", data: { stripe: 'label' } %>
    </div>
    <div class="col-md-3">
      <%= p.select :card_expires_month,
      options_for_select(Payment.month_options),
      { include_blank: 'Month' },
      "data-stripe" => "exp-month",
      class: "form-control", required: true %>
    </div>
    <div class="col-md-3">
      <%= p.select :card_expires_year,
      options_for_select(Payment.year_options.push),
      { include_blank: 'Year' },
      class: "form-control",
        data: { stripe: "exp-year"}, required: true %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
  <br />
  <div class="row col-md-12">
    <%= f.submit 'Update Plan', class: "btn btn-primary", id: 'update_plan' %>
  </div>
  <% end %>