config/routes.rb
Rails.application.routes.draw do

  resources :user_projects

  resources :artifacts

  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end

  resources :members

  get 'home/index'

  root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match 'user/confirmation' => 'confirmations#update', :via => :put,
    :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan

  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :tenant
  validates_uniqueness_of :title
  validate :free_plan_can_only_have_one_project
  has_many :artifacts, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects

  def free_plan_can_only_have_one_project
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
      errors.add(:base, 'Free plans cannot have more than one project')
    end
  end

  def self.by_user_plan_and_tenant(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin?
        tenant.projects
      else
        user.projects.where(tenant_id: tenant.id)
      end
    else
      if user.is_admin?
        tenant.projects.order(:id).limit(1)
      else
        user.projects.where(tenant_id: tenant.id).order(:id).limit(1)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :users, :add_user]
  before_action :set_tenant, only: [:show, :edit, :update, :new, :create, :users, :add_user]
  before_action :verify_tenant

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.by_user_plan_and_tenant(params[:tenant_id], current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_url, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def users
    @project_users = (@project.users + (User.where(tenant_id: @tenant.id, is_admin: true))) - [current_user]
    @other_users = @tenant.users.where(is_admin: false) - (@project_users + [current_user])
  end

  def add_user
    @project_user = UserProject.new(user_id: params[:user_id], project_id: @project.id)
    respond_to do |format|
      if @project_user.save
        format.html { redirect_to users_tenant_project_url(id: @project.id,
          tenant_id: @project.tenant_id),
        notice: 'User was successfully added to project' }
      else
        format.html { redirect_to users_tenant_project_url(id: @project.id,
          tenant_id: @project.tenant_id),
        error: 'User was not added to project' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :tenant_id)
    end

    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])
    end

    def verify_tenant
      unless params[:tenant_id] == Tenant.current_tenant_id.to_s
        redirect_to :root, flash: { error: 'You are not authorized to access any organization other than your own'}
      end
    end
  end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@tenant, @project], html: { class: "form-horizontal project" } do |f| %>

<% if @project.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title, class: 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :details, class: 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :details, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :expected_completion_date, class: 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :expected_completion_date, class: 'form-control datepicker' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.hidden_field :tenant_id, value: params[:tenant_id], class: 'form-control' %>
    <br />
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
    root_path, class: 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/projects/_list.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if @projects.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:title) %></th>
        <th><%= model_class.human_attribute_name(:details) %></th>
        <th><%= model_class.human_attribute_name(:expected_completion_date) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, tenant_project_path(project, tenant_id: @tenant.id), class: 'main-link' %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_completion_date %></td>
        <td>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
          edit_tenant_project_path(project, tenant_id: @tenant.id), class: 'btn btn-default btn-xs' %>
          <%= link_to 'Edit Users', users_tenant_project_path(project, tenant_id: @tenant.id), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
          tenant_project_path(project, tenant_id: @tenant.id),
          method: :delete,
          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
          class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
</table>
<% else %>
  <p class="lead">You don't have any projects</p>
<% end %>

<% if (@tenant.can_create_projects?) %>
  <%= link_to 'New Project', new_tenant_project_path(tenant_id: @tenant.id),
                                                 class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h3><%= @project.title %></h3>
  <h3><small>Organization - <%= tenant_name @project.tenant_id %></small></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @project.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expected_completion_date) %>:</strong></dt>
  <dd><%= @project.expected_completion_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tenant_id) %>:</strong></dt>
  <dd><%= @project.tenant_id %></dd>
</dl>

<h3>Artifacts</h3>
<%= render 'artifacts/list', artifacts: @project.artifacts %>
<br />
<br />

<%= link_to '< Back to Organization Home', root_path, class: 'btn btn-default' %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tenant_project_path(
                        project: @project,
                        tenant: @project.tenant_id),
                        class: 'btn btn-default' %>
<%= link_to 'Edit Project Users', users_tenant_project_path(tenant_id: @project.tenant_id, id: @project.id), :class => 'btn btn-default' %>


<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          tenant_project_path(@project, @project.tenant_id),
                          :method => 'delete',
                          :data => {
                            :confirm => t('.confirm',
                            :default => t("helpers.links.confirm",
                            :default => 'Are you sure?')) },
                            class: 'btn btn-danger' %>

app/views/projects/users.html.erb
<div class="page-header">
  <h3>Users for Project <%= @project.title %></h3>
  <strong>(Other than yourself)</strong>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @project_users.each do |project_user| %>
    <tr>
      <td><%= project_user.email %></td>
      <td>
        <% if !project_user.is_admin? %>
        <%= link_to 'Remove', user_project_path(project_user.user_projects.find_by(
                          project_id: @project.id),
                          tenant_id: @project.tenant_id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm',
                          :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<h3>Users to add to Project <%= @project.title %></h3>
<strong>(Admins don't need to be added)</strong>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @other_users.each do |other_user| %>
    <tr>
      <td><%= other_user.email %></td>
      <td>
        <%= link_to 'Add',
        add_user_tenant_project_path(id: @project.id, tenant_id: @project.tenant_id, user_id: other_user.id),
        :method => :put,
        :class => 'btn btn-xs btn-success' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', tenant_project_path(id: @project.id,
                            tenant_id: @project.tenant_id), :class => 'btn btn-primary' %>