config/routes.rb
Rails.application.routes.draw do

  resources :user_projects

  resources :artifacts

  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end

  resources :members

  get 'home/index'

  root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match 'user/confirmation' => 'confirmations#update', :via => :put,
    :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan

  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/views/common/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span>
      <%= link_to ("<i class='fa fa-rocket'></i>" + 'Project Management App').html_safe, root_path, class: 'navbar-brand' %>
    </span>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if current_user && current_user.is_admin? %>
        <li>
          <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe,
          new_member_path,
          class: 'navbar-link btn btn-primary' %>
        </li>
        <li>
        <%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path, class: 'btn btn-primary navbar-link' %>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-right col-md-4">

        <% if current_user %>
        <li class="col-md-8 user-name">
          <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
        </li>
        <li class="col-md-1"> </li>
        <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
        <% else %>
        <li class="col-md-4 pull-right">
          <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
        </li>
        <% end %>

      </ul>

    </div>
  </div>
</div>